const products = [
  {
    id: 1,
    name: "T-shirt",
    category: "Cloths",
    price: 1199,
    stock_quantity: 100,
  },
  {
    id: 2,
    name: "Smartphone",
    category: "Electronics",
    price: 37499,
    stock_quantity: 50,
  },
  {
    id: 3,
    name: "Book",
    category: "Books",
    price: 929,
    stock_quantity: 25,
  },
  {
    id: 4,
    name: "Headphones",
    category: "Electronics",
    price: 2965,
    stock_quantity: 30,
  },
  {
    id: 5,
    name: "Sneakers",
    category: "Footwear",
    price: 5999,
    stock_quantity: 10,
  },
  {
    id: 6,
    name: "Laptop",
    category: "Electronics",
    price: 67499,
    stock_quantity: 20,
  },
  {
    id: 7,
    name: "Jeans",
    category: "Cloths",
    price: 2249,
    stock_quantity: 80,
  },
  {
    id: 8,
    name: "Watch",
    category: "Accessories",
    price: 13499,
    stock_quantity: 45,
  },
  {
    id: 9,
    name: "Backpack",
    category: "Bags",
    price: 3749,
    stock_quantity: 25,
  },
  {
    id: 10,
    name: "Sunglasses",
    category: "Accessories",
    price: 1499,
    stock_quantity: 65,
  },
  {
    id: 11,
    name: "Desktop Computer",
    category: "Electronics",
    price: 97499,
    stock_quantity: 15,
  },
  {
    id: 12,
    name: "Dress",
    category: "Cloths",
    price: 2999,
    stock_quantity: 55,
  },
  {
    id: 13,
    name: "Gaming Console",
    category: "Electronics",
    price: 26249,
    stock_quantity: 25,
  },
  {
    id: 14,
    name: "Coffee Maker",
    category: "Home Appliances",
    price: 5599,
    stock_quantity: 40,
  },
  {
    id: 15,
    name: "Running Shoes",
    category: "Footwear",
    price: 8099,
    stock_quantity: 70,
  },
];

export default products;
