const orders = [
  {
    orderId: "ID03",
    customerName: "Sophia Johnson",
    orderDate: "2024-05-14",
    orderStatus: "Shipped",
    deliveryDate: "2024-05-20",
    deliveryAddress: "789 Oak St, Chicago",
    products: [
      {
        id: 5,
        name: "Sneakers",
        category: "Footwear",
        price: 5999,
        quantity: 1,
      },
      {
        id: 6,
        name: "Laptop",
        category: "Electronics",
        price: 67499,
        quantity: 1,
      },
    ],
  },
  {
    orderId: "ID04",
    customerName: "Noah Williams",
    orderDate: "2024-05-16",
    orderStatus: "Processing",
    deliveryDate: "2024-05-22",
    deliveryAddress: "101 Pine St, San Francisco",
    products: [
      { id: 7, name: "Jeans", category: "Clothing", price: 2249, quantity: 2 },
      {
        id: 8,
        name: "Watch",
        category: "Accessories",
        price: 13499,
        quantity: 1,
      },
    ],
  },
  {
    orderId: "ID05",
    customerName: "Olivia Brown",
    orderDate: "2024-05-18",
    orderStatus: "Delivered",
    deliveryDate: "2024-05-25",
    deliveryAddress: "222 Maple St, Seattle",
    products: [
      { id: 9, name: "Backpack", category: "Bags", price: 3749, quantity: 1 },
      {
        id: 10,
        name: "Sunglasses",
        category: "Accessories",
        price: 1499,
        quantity: 1,
      },
    ],
  },
  {
    orderId: "ID06",
    customerName: "William Lee",
    orderDate: "2024-05-18",
    orderStatus: "Pending",
    deliveryDate: "2024-05-27",
    deliveryAddress: "333 Cherry St, Miami",
    products: [
      {
        id: 11,
        name: "Desktop Computer",
        category: "Electronics",
        price: 97499,
        quantity: 1,
      },
      { id: 12, name: "Dress", category: "Clothing", price: 2999, quantity: 1 },
    ],
  },
  {
    orderId: "ID07",
    customerName: "Ava Miller",
    orderDate: "2024-05-22",
    orderStatus: "Processing",
    deliveryDate: "2024-05-27",
    deliveryAddress: "444 Elm St, Boston",
    products: [
      {
        id: 13,
        name: "Gaming Console",
        category: "Electronics",
        price: 26249,
        quantity: 1,
      },
      {
        id: 14,
        name: "Coffee Maker",
        category: "Home Appliances",
        price: 5599,
        quantity: 1,
      },
    ],
  },
  {
    orderId: "ID08",
    customerName: "James Garcia",
    orderDate: "2024-05-24",
    orderStatus: "Delivered",
    deliveryDate: "2024-06-01",
    deliveryAddress: "555 Oak St, Atlanta",
    products: [
      {
        id: 15,
        name: "Running Shoes",
        category: "Footwear",
        price: 8099,
        quantity: 1,
      },
      {
        id: 1,
        name: "T-shirt",
        category: "Clothing",
        price: 1199,
        quantity: 1,
      },
    ],
  },
  {
    orderId: "ID09",
    customerName: "Isabella Rodriguez",
    orderDate: "2024-05-24",
    orderStatus: "Shipped",
    deliveryDate: "2024-06-03",
    deliveryAddress: "666 Pine St, Houston",
    products: [
      {
        id: 2,
        name: "Smartphone",
        category: "Electronics",
        price: 37499,
        quantity: 1,
      },
      { id: 3, name: "Book", category: "Books", price: 929, quantity: 1 },
    ],
  },
  {
    orderId: "ID010",
    customerName: "Logan Martinez",
    orderDate: "2024-05-28",
    orderStatus: "Processing",
    deliveryDate: "2024-06-05",
    deliveryAddress: "777 Maple St, Dallas",
    products: [
      {
        id: 4,
        name: "Headphones",
        category: "Electronics",
        price: 2965,
        quantity: 1,
      },
      {
        id: 5,
        name: "Sneakers",
        category: "Footwear",
        price: 5999,
        quantity: 1,
      },
    ],
  },
];
export default orders;
